compatibility:
  disabled: false
deepcopy:
  disabled: false
  headerFilePath: ../hack/empty.txt
  outputFileBaseName: zz_generated.deepcopy
schemapatch:
  disabled: false
  requiredFeatureSets:
  - ""
  - "Default"
  - "TechPreviewNoUpgrade"
swaggerdocs:
  disabled: false
  commentPolicy: Warn
  outputFileName: zz_generated.swagger_doc_generated.go
