//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildInputs) DeepCopyInto(out *BuildInputs) {
	*out = *in
	out.FinalImagePushSecret = in.FinalImagePushSecret
	out.FinalImagePullSecret = in.FinalImagePullSecret
	if in.Containerfile != nil {
		in, out := &in.Containerfile, &out.Containerfile
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildInputs.
func (in *BuildInputs) DeepCopy() *BuildInputs {
	if in == nil {
		return nil
	}
	out := new(BuildInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSecretObjectReference) DeepCopyInto(out *ImageSecretObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSecretObjectReference.
func (in *ImageSecretObjectReference) DeepCopy() *ImageSecretObjectReference {
	if in == nil {
		return nil
	}
	out := new(ImageSecretObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCOObjectReference) DeepCopyInto(out *MCOObjectReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCOObjectReference.
func (in *MCOObjectReference) DeepCopy() *MCOObjectReference {
	if in == nil {
		return nil
	}
	out := new(MCOObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNode) DeepCopyInto(out *MachineConfigNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNode.
func (in *MachineConfigNode) DeepCopy() *MachineConfigNode {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeList) DeepCopyInto(out *MachineConfigNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfigNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeList.
func (in *MachineConfigNodeList) DeepCopy() *MachineConfigNodeList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeSpec) DeepCopyInto(out *MachineConfigNodeSpec) {
	*out = *in
	out.Node = in.Node
	out.Pool = in.Pool
	out.ConfigVersion = in.ConfigVersion
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeSpec.
func (in *MachineConfigNodeSpec) DeepCopy() *MachineConfigNodeSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeSpecMachineConfigVersion) DeepCopyInto(out *MachineConfigNodeSpecMachineConfigVersion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeSpecMachineConfigVersion.
func (in *MachineConfigNodeSpecMachineConfigVersion) DeepCopy() *MachineConfigNodeSpecMachineConfigVersion {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeSpecMachineConfigVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeStatus) DeepCopyInto(out *MachineConfigNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ConfigVersion = in.ConfigVersion
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeStatus.
func (in *MachineConfigNodeStatus) DeepCopy() *MachineConfigNodeStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigNodeStatusMachineConfigVersion) DeepCopyInto(out *MachineConfigNodeStatusMachineConfigVersion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigNodeStatusMachineConfigVersion.
func (in *MachineConfigNodeStatusMachineConfigVersion) DeepCopy() *MachineConfigNodeStatusMachineConfigVersion {
	if in == nil {
		return nil
	}
	out := new(MachineConfigNodeStatusMachineConfigVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigPoolReference) DeepCopyInto(out *MachineConfigPoolReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigPoolReference.
func (in *MachineConfigPoolReference) DeepCopy() *MachineConfigPoolReference {
	if in == nil {
		return nil
	}
	out := new(MachineConfigPoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuild) DeepCopyInto(out *MachineOSBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuild.
func (in *MachineOSBuild) DeepCopy() *MachineOSBuild {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOSBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildList) DeepCopyInto(out *MachineOSBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineOSBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildList.
func (in *MachineOSBuildList) DeepCopy() *MachineOSBuildList {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOSBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildSpec) DeepCopyInto(out *MachineOSBuildSpec) {
	*out = *in
	out.MachineConfigPool = in.MachineConfigPool
	in.BuildInputs.DeepCopyInto(&out.BuildInputs)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildSpec.
func (in *MachineOSBuildSpec) DeepCopy() *MachineOSBuildSpec {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSBuildStatus) DeepCopyInto(out *MachineOSBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RenderedMachineOSImage = in.RenderedMachineOSImage
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.BuildHistory != nil {
		in, out := &in.BuildHistory, &out.BuildHistory
		*out = make([]PriorMachineOSBuilds, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSBuildStatus.
func (in *MachineOSBuildStatus) DeepCopy() *MachineOSBuildStatus {
	if in == nil {
		return nil
	}
	out := new(MachineOSBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOSImageReference) DeepCopyInto(out *MachineOSImageReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOSImageReference.
func (in *MachineOSImageReference) DeepCopy() *MachineOSImageReference {
	if in == nil {
		return nil
	}
	out := new(MachineOSImageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorMachineOSBuilds) DeepCopyInto(out *PriorMachineOSBuilds) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorMachineOSBuilds.
func (in *PriorMachineOSBuilds) DeepCopy() *PriorMachineOSBuilds {
	if in == nil {
		return nil
	}
	out := new(PriorMachineOSBuilds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedMachineConfigReference) DeepCopyInto(out *RenderedMachineConfigReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedMachineConfigReference.
func (in *RenderedMachineConfigReference) DeepCopy() *RenderedMachineConfigReference {
	if in == nil {
		return nil
	}
	out := new(RenderedMachineConfigReference)
	in.DeepCopyInto(out)
	return out
}
